---

- hosts: jboss_amq_rhel_hosts
  gather_facts: true
  become: true
  become_user: "{{ ansible_rhel_user }}"
  become_method: sudo
  
  # Set capabilities to install
  vars:
    # redhat-cop.jboss_common
    rhsm_subscribe_host: False
    rhsm_disable_existing_repositories: False
    rhsm_enable_required_repositories: False
    # redhat-cop.jboss_amq
    amq_version: 7.6.0
    jboss_amq_artifact_source: https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=79671
    role_install_broker: true
    role_install_interconnect: false

  vars_prompt:
    - name: "rhn_username"
      prompt: "Enter Your Red Hat Customer Portal Username"
      private: no

    - name: "rhn_password"
      prompt: "Enter Your Red Hat Customer Portal Password"
      private: yes

  roles:
    - role: redhat-cop.jboss_common
    # Two AMQ Brokers in Master/Slave topology with a shared storage
    - {
        role: redhat-cop.jboss_amq,
        amq_broker_name: master,
        amq_broker_shared_storage: True
      }
    - {
        role: redhat-cop.jboss_amq,
        amq_broker_name: slave,
        amq_broker_shared_storage: True,
        amq_broker_replicate: True,
        amq_broker_ports_offset_enabled: True,
        amq_broker_ports_offset: 100
      }
