- hosts: jboss_bxms_eap_centos_hosts
  remote_user: "{{ ansible_centos_user }}"
  sudo: true
  gather_facts: true

  vars:
    transfer_method: csp-to-host

  vars_prompt:
  - name: "rhn_username"
    prompt: "Enter Your Red Hat Customer Portal Username"
    private: no

  - name: "rhn_password"
    prompt: "Enter Your Red Hat Customer Portal Password"
    private: yes

  roles:
  - common
  - jboss_eap
  - jboss_bxms
